language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby
gemfile:
  - gemfiles/rapporteur2.gemfile
  - gemfiles/rapporteur3.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rapporteur2.gemfile
notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "AVi2J9hq3ZBvNt9/eDwslgGfqyhURtcoJFlHScOgffK+9woQOeJXDQcpqxxE\nto7C1lnRn8c0VE2Z0gP5CPZUzHrLnlqUYZkyL4BuHtO29HPgrYT1SPuc80zo\nFv6o0TEzBmOUDxlrmSq8PBZbW1PkBDHWmMf3Tcs/zNjaL6QglLY="
